### ISSUE TITLE
Factory method with support for generic types

### ISSUE THREAD

**Issue by luigidalmare** [objecttrouve/convenience-matchers#2]
When I have an object that has a generic type i need to remove the type parameter from actual object before passing to matcher.

something like
```
List<List<String>> list =...
assertThat(list, is(anIterableOf(List.class)
```
doesnt compile. 

i have to remove the string type param

Is it possible to keep the string param?

**Comment by objecttrouve** [comment]
Sounds like a reasonable idea. 
Let me think about it. It's a long time since I last touched this...

**Comment by objecttrouve** [comment]
PR fixed the issue, I suppose. Thanks @luigidalmare!
